** 1.Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.**

In [1]:
l=[x for x in range(2000,3201) if (x%5!=0 and x%7==0) ]
l

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

**2. Write a program which can compute the factorial of a given numbers. The results should be printed in a comma-separated sequence on a single line.**

In [2]:
ipnum1=input("Enter the number to find the factorial :")
ipnum=int(ipnum1)
factorial=1
if (ipnum>0):
    for i in range(1,ipnum+1):
         factorial=factorial*i
    print("Factorial for the given number " +str(ipnum) + " is " +str(factorial) )
else:
    print("Factorial for the given number: " +str(ipnum) +" does not exist" )

Enter the number to find the factorial :5
Factorial for the given number 5 is 120


**3. With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included) and then the program should print the dictionary.**

In [3]:
num=int(input("Enter the number : "))
dict1=dict()
for i in range(1,num+1):
    key=i;
    value=i*i;
    dict1.update({key:value})
print(dict1)

Enter the number : 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


**4. Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.**

In [4]:
l1=(input("Enter the list of numbers : "))
l2=l1.split(',')
t1=tuple(l2)
print(l2,t1)

Enter the list of numbers : 1,2,3,4,5
['1', '2', '3', '4', '5'] ('1', '2', '3', '4', '5')


**5. Define a class which has at least two methods:
getString: to get a string from console input
printString: to print the string in upper case.**

In [5]:
class stringHandling:
    def __init__(self,a):
        self.a=a
        
    def getString(self):
        self.strin=input("Enter the input string :")
        
    def printstring(self):
        print("The string to print is : ",(self.strin).upper())
s1=stringHandling("a")
s1.getString()
s1.printstring()

Enter the input string :hello world
The string to print is :  HELLO WORLD


**6. Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H: C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.**

In [6]:
import math
C=50
H=30
Din=input("enter the value for D in comma seperated format")
Din=Din.split(',')
root=[]
for i in Din:
    root.append(int(math.sqrt((2*C*int(i))/H)))
root

enter the value for D in comma seperated format100,150,250


[18, 22, 28]

**7. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Suppose the following inputs are given to the program: 3, 5
Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]
Hints: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.**

In [7]:
nums=input("Enter X,Y values :")
x,y=nums.split(',')
x=int(x)
y=int(y)
L1=[]
for i in range(x):
    l2=[]
    for j in range(y):
        l2.append(i*j)
    L1.append(l2)
L1

Enter X,Y values :3,5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

**8. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
Suppose the input is supplied to the program: without, hello, bag, world
Then, the output should be: bag, hello, without, world
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [8]:
wordin=input("Enter the words :")
words=[]
words=wordin.split(',')
word=sorted(words)
word

Enter the words :without,hello,bag,world


['bag', 'hello', 'without', 'world']

** 9.Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.Suppose the input is supplied to the program: Hello world
Practice makes perfect
Then, the output should be: HELLO WORLD
PRACTICE MAKES PERFECT
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [9]:
l = []
while True:
    s = input("Enter the input sentences :")
    if s:
        l.append(s.upper())
    else:
        break;

for upper_sentence in l:
    print(upper_sentence)

Enter the input sentences :hello world
Enter the input sentences :practice makes perfect
Enter the input sentences :
HELLO WORLD
PRACTICE MAKES PERFECT


**10. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
Suppose the input is supplied to the program: hello world and practice makes perfect and hello world again
Then, the output should be: again and hello makes perfect practice world**

In [10]:
string1=input("Enter whitespace seperated words")
strlst=string1.split(' ')
strop=list(dict.fromkeys(strlst))
strop.sort()
strop

Enter whitespace seperated wordshello world and practice makes perfect and hello world again


['again', 'and', 'hello', 'makes', 'perfect', 'practice', 'world']

**11. Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
Suppose the input is supplied to the program: 0100,0011,1010,1001
Then the output should be: 1010
Notes: Assume the data is input by console.
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [11]:
binnums=input("Enter the comma seperated 4 digit binary numbers :")
binlist=binnums.split(',')
intlist=[]
for i in binlist:
    j=int(i,2)
    if (j%5==0):
        intlist.append(i)
intlist

Enter the comma seperated 4 digit binary numbers :0100,0011,1010,1001


['1010']

**12. Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.
The numbers obtained should be printed in a comma-separated sequence on a single line.
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [12]:
ipnums=input("Enter the range of numbers seperated by comma")
num1,num2=ipnums.split(',')
num1=int(num1)
num2=int(num2)
evenlst=[]
oddcnt=0
oddset={'1','3','5','7','9'}
for i in range(num1,num2+1):
    j=str(i)    
    if any((c in oddset) for c in j):
        oddcnt=oddcnt+1
    else:
        evenlst.append(i)
evenlst

Enter the range of numbers seperated by comma1000,3000


[2000,
 2002,
 2004,
 2006,
 2008,
 2020,
 2022,
 2024,
 2026,
 2028,
 2040,
 2042,
 2044,
 2046,
 2048,
 2060,
 2062,
 2064,
 2066,
 2068,
 2080,
 2082,
 2084,
 2086,
 2088,
 2200,
 2202,
 2204,
 2206,
 2208,
 2220,
 2222,
 2224,
 2226,
 2228,
 2240,
 2242,
 2244,
 2246,
 2248,
 2260,
 2262,
 2264,
 2266,
 2268,
 2280,
 2282,
 2284,
 2286,
 2288,
 2400,
 2402,
 2404,
 2406,
 2408,
 2420,
 2422,
 2424,
 2426,
 2428,
 2440,
 2442,
 2444,
 2446,
 2448,
 2460,
 2462,
 2464,
 2466,
 2468,
 2480,
 2482,
 2484,
 2486,
 2488,
 2600,
 2602,
 2604,
 2606,
 2608,
 2620,
 2622,
 2624,
 2626,
 2628,
 2640,
 2642,
 2644,
 2646,
 2648,
 2660,
 2662,
 2664,
 2666,
 2668,
 2680,
 2682,
 2684,
 2686,
 2688,
 2800,
 2802,
 2804,
 2806,
 2808,
 2820,
 2822,
 2824,
 2826,
 2828,
 2840,
 2842,
 2844,
 2846,
 2848,
 2860,
 2862,
 2864,
 2866,
 2868,
 2880,
 2882,
 2884,
 2886,
 2888]

**13. Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the input is supplied to the program: hello world! 123
Then, the output should be: LETTERS 10
DIGITS 3
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [13]:
string1=input("Enter the input string")
ltrcnt=0
dgtcnt=0
for i in string1:
    if (i.isalpha())==True:        
        ltrcnt=ltrcnt+1
    elif (i.isnumeric())==True:
        dgtcnt=dgtcnt+1
print("LETTERS " + str(ltrcnt) + " DIGITS " + str(dgtcnt))

Enter the input stringhello world! 123
LETTERS 10 DIGITS 3


**14. Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.
Suppose the input is supplied to the program: Hello world!
Then, the output should be: UPPER CASE 1
LOWER CASE 9
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [14]:
string1=input("Enter the input string :")
uprcnt=0
lwrcnt=0
for i in string1:
    if (i.isalpha())==True:
        if (i.isupper())==True:        
            uprcnt=uprcnt+1
        else:
            lwrcnt=lwrcnt+1
print("UPPER CASE " + str(uprcnt) + " LOWER CASE " + str(lwrcnt))

Enter the input string :Hello world!
UPPER CASE 1 LOWER CASE 9


**15. Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.
Suppose the input is supplied to the program: 9
Then, the output should be: 11106
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [15]:
a=int(input("Enter the number :"))
rslt=(a+(a**2)+(a**3)+(a**4))
print(rslt)

Enter the number :9
7380


**16. Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers.
Suppose the input is supplied to the program: 1,2,3,4,5,6,7,8,9
Then, the output should be: 1, 3, 5, 7, 9
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [16]:
input1=input("Enter the comma seperated list of numbers")
input2=input1.split(',')
l1=[int(i) for i in input2]
l2=[j**2 for j in l1 if((j%2)!=0)]
l2

Enter the comma seperated list of numbers1,2,3,4,5,6,7,8,9


[1, 9, 25, 49, 81]

**17. Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following:
D 100
W 200
--D means deposit while W means withdrawal.
Suppose the input is supplied to the program:
D 300
W 200
D 100
Then, the output should be: 500
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [17]:
log_input=input("Enter the transaction log detiails :")
total=0
log=log_input.split(' ')
for i in range(len(log)):
    if log[i]=='D':
        total=total+int(log[i+1])
    elif log[i]=='W':
        total=total-int(log[i+1])       
print("Net balance :"+str(total))

Enter the transaction log detiails :D 300 W 200 D 100
Net balance :200


**18. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.
Following are the criteria for checking the password
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.
If the following passwords are given as input to the program: ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be: ABd1234@1
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [18]:
import re
password=input("Enter a sequence of password :")
password_list=password.split(',')
for i in password_list:
    if(len(i) >=6 and len(i) <=12):
        if(bool(re.match('^(?=.*[0-9]$)(?=.*[a-zA-Z])(?=.*[$#@])', i))):
            print(i)

Enter a sequence of password :ABd1234@1,a F1#,2w3E,2We3345
ABd1234@1


**19. You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
1: Sort based on name;
2: Then sort based on age;
3: Then sort by score.
The priority is that name > age > score.
If the following tuples are given as input to the program:
Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]
Hints: In case of input data being supplied to the question, it should be assumed to be a console input. We use itemgetter to enable multiple sort keys.**

In [19]:
from operator import itemgetter
ip=input ("Enter the comma seperated tuples in the form of (Name, age, score) ")
pd=[]
for tup in ip.split(' '):
    pd.append(tuple(tup.split(",")))
srtd=sorted(pd,key=itemgetter(0,1,2))
srtd

Enter the comma seperated tuples in the form of (Name, age, score) Tom,19,80 John,20,90 Jony,17,91 Jony,17,93 Json,21,85


[('John', '20', '90'),
 ('Jony', '17', '91'),
 ('Jony', '17', '93'),
 ('Json', '21', '85'),
 ('Tom', '19', '80')]

**20. Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.
Hints: Consider use yield**

In [20]:
class gendiv7:
    def __init__(self, max):
        self.max = max
    def PowTwoGen(self):
        for i in range(self.max):
            if(i%7==0):
                yield i
g1=gendiv7(70)
g=g1.PowTwoGen()
for i in g:
    print(i)

0
7
14
21
28
35
42
49
56
63


**21. A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps. The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
¡The
numbers after the direction are steps. Please write a program to compute the distance from current position after a sequence of movement and original point. If the distance is a float, then just print the nearest integer.
If the following tuples are given as input to the program:
UP 5
DOWN 3
LEFT 3
RIGHT 2
Then, the output of the program should be: 2
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [21]:
import math
x1,y1=0,0
x2,y2=0,0
ip=input("Enter the directions: ")
directions=ip.split(' ')
for i in range(len(directions)):
    if(directions[i]=='UP'):
        y2=y2+int(directions[i+1])
    elif(directions[i]=='DOWN'):
        y2=y2-int(directions[i+1])
    elif(directions[i]=='LEFT'):
        x2=x2-int(directions[i+1])
    elif(directions[i]=='RIGHT'):
        x2=x2+int(directions[i+1])   
distance=int(math.sqrt(((x2-x1)**2)+((y2-y1)**2)))
print(distance)

Enter the directions: UP 5 DOWN 3 LEFT 3 RIGHT 2
2


**22. Write a program to compute the frequency of the words from the input. The output should output after sorting the key alphanumerically.
Suppose the input is supplied to the program:
New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
Then, the output should be:
2:2
3.:1
3?:1
New:1
Python:5
Read:1
and:1
between:1
choosing:1
or:2
to:1
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.**

In [22]:
str1=input("Enter the string to be counted ")
lst1=str1.split(' ')
dict1=dict()
for i in lst1:
    cnt1=str1.count(i)
    dict1.update({i:cnt1})
for key in sorted(dict1):
    print(key,dict1[key])

Enter the string to be counted New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
2 2
3. 1
3? 1
New 1
Python 5
Read 1
and 1
between 1
choosing 1
or 2
to 1


**23. Write a method which can calculate square value of number
Hints: Using the ** operator**

In [23]:
numin=input("Enter the number to be squared")
num1=int(numin)
numout=num1**2
print(numout)

Enter the number to be squared8
64


**24. Python has many built-in functions, and if you do not know how to use it, you can read document online or find some books. But Python has a built-in document function for every
built-in functions. Please write a program to print some Python built-in functions documents, such as abs(), int(), raw_input() And add document for your own function
Hints: The built-in document method is __doc__**

In [24]:
print(abs.__doc__)
print("=======================================================================")
print(int.__doc__)
print("=======================================================================")
#print(raw_input().__doc__) #raw_input is no longer included in python
def multiply( a , b):
    """Returns product of two inputs
    """
    c=a*b
    return c
print(multiply.__doc__)

Return the absolute value of the argument.
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4
Returns product of two inputs
    


**25. Define a class, which have a class parameter and have a same instance parameter.
Hints: Define a instance parameter, need add it in __init__ method
You can init a object with construct parameter or set the value later**

In [25]:
class dummy:
    def __init__(self,a):
        self.a = a
a=dummy("Boring")

**26. Define a function which can compute the sum of two numbers.
Hints: Define a function with two numbers as arguments. You can compute the sum in the function and return the value.**

In [26]:
def addnums(a,b):
    c=int(a)+int(b)
    return(c)
inputs=input("Enter the 2 numbers to be added :")
num1,num2=inputs.split(',')
print(addnums(num1,num2))

Enter the 2 numbers to be added :120,147
267


**27. Define a function that can convert a integer into a string and print it in console.
Hints: Use str() to convert a number to string.**

In [27]:
num1=int(input("Enter the number to be converted : "))
#num1= 10 #edit the number which you want to convert to integer
str1=str(num1)
print(str1,type(str1))

Enter the number to be converted : 54
54 <class 'str'>


**28. Define a function that can convert a integer into a string and print it in console.
Hints: Use str() to convert a number to string.**

In [28]:
## Repeat of the qstn no 27
num1=int(input("Enter the numbers to be converted : "))
#num1= 10 #edit the number which you want to convert to integer
str1=str(num1)
print(str1,type(str1))

Enter the numbers to be converted : 27
27 <class 'str'>


**29. Define a function that can receive two integral numbers in string form and compute their sum and then print it in console.
Hints: Use int() to convert a string to integer.**

In [29]:
##qstn no 26 repeat
def addnums(a,b):
    c=int(a)+int(b)
    return(c)
inputs=input("Enter the 2 numbers to be added :")
num1,num2=inputs.split(',')
print(addnums(num1,num2))

Enter the 2 numbers to be added :120,55
175


**30. Define a function that can accept two strings as input and concatenate them and then print it in console.
Hints: Use + to concatenate the strings**

In [30]:
input1=input("enter the 2 strings seperated by comma")
str1,str2=input1.split(',')
print(str1+str2)

enter the 2 strings seperated by commaLaaa,deee
Laaadeee


**31. Define a function that can accept two strings as input and print the string with maximum length in console. If two strings have the same length, then the function should print al l strings line by line.
Hints: Use len() function to get the length of a string**

In [31]:
input1=input("Enter 2 strings seperated by comma: ")
str1,str2=input1.split(',')
if(len(str1)>len(str2)):
 print(str1)
elif(len(str1)<len(str2)):
 print(str2)
else:
 print(str1+'\n'+str2)

Enter 2 strings seperated by comma: Helloworld,Bye
Helloworld


**32. Define a function that can accept an integer number as input and print the "It is an even number" if the number is even, otherwise print "It is an odd number".
Hints: Use % operator to check if a number is even or odd.**

In [32]:
input1=input("enter the number :")
# num1=int(input1)
if(int(input1)%2==0):
    print("Its an even number")
else:
    print("Its an odd number")

enter the number :15
Its an odd number


**33. Define a function which can print a dictionary where the keys are numbers between 1 and 3 (both included) and the values are square of keys.
Hints: Use dict[key]=value pattern to put entry into a dictionary.Use * * operator to get power of a number.**

In [33]:
def createdict(a,b):
    dict1=dict()
    for i in range(a,b+1):
        dict1[i]=i**2
    return(dict1)
opdict=createdict(1,3)
opdict

{1: 1, 2: 4, 3: 9}

**34. Define a function which can print a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys.
Hints: Use dict[key]=value pattern to put entry into a dictionary.
Use ** operator to get power of a number. Use range() for loops.**

In [34]:
def createdict(a,b):
    dict1=dict()
    for i in range(a,b+1):
        dict1[i]=i**2
    return(dict1)
opdict=createdict(1,20)
opdict

{1: 1,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 10: 100,
 11: 121,
 12: 144,
 13: 169,
 14: 196,
 15: 225,
 16: 256,
 17: 289,
 18: 324,
 19: 361,
 20: 400}

**35. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the values only.
Hints: Use dict[key]=value pattern to put entry into a dictionary. Use ** operator to get power of a number. Use range() for loops. Use keys() to iterate keys in the dictionary. Also we can use item() to get key/value pairs.**

In [35]:
def createdict(a,b):
    dict1=dict()
    for i in range(a,b+1):
        dict1[i]=i**2
    return(dict1)
opdict=createdict(1,20)
print(opdict.values())

dict_values([1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])


**36. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the keys only.
Hints: Use dict[key]=value pattern to put entry into a dictionary. Use ** operator to get power of a number. Use range() for loops. Use keys() to iterate keys in the dictionary. Also we can use item() to get key/value pairs.**

In [36]:
def createdict(a,b):
    dict1=dict()
    for i in range(a,b+1):
        dict1[i]=i**2
    return(dict1)
opdict=createdict(1,20)
print(opdict.keys())

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


**37. Define a function which can generate and print a list where the values are square of numbers between 1 and 20 (both included).
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list.**

In [37]:
oplst=[]
def sqrnums(a,b):
    lst=[]
    for i in range(a,b+1):
        lst.append(i**2)
    return lst
oplst=sqrnums(1,20)
oplst

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

**38. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the first 5 elements in the list.
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use [n1:n2] to slice a list**

In [38]:
oplst=[]
def sqrnums(a,b):
    lst=[]
    for i in range(a,b):
        lst.append(i**2)
    return lst
oplst=sqrnums(1,21)
oplst[0:5]

[1, 4, 9, 16, 25]

**39. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the last 5 elements in the list.
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use [n1:n2] to slice a list**

In [39]:
oplst=[]
def sqrnums(a,b):
    lst=[]
    for i in range(a,b):
        lst.append(i**2)
    return lst
oplst=sqrnums(1,21)
oplst[-5:]

[256, 289, 324, 361, 400]

**40. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print all values except the first 5 elements in the list.
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use [n1:n2] to slice a list**

In [40]:
oplst=[]
def sqrnums(a,b):
    lst=[]
    for i in range(a,b):
        lst.append(i**2)
    return lst
oplst=sqrnums(1,21)
oplst[5:]

[36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

**41. Define a function which can generate and print a tuple where the value are square of numbers between 1 and 20 (both included).
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use tuple() to get a tuple from a list.**

In [41]:
t1=()
oplst=[]
def sqrnums(a,b):
    lst=[]
    for i in range(a,b):
        lst.append(i**2)
    return lst
oplst=sqrnums(1,21)
t1=tuple(oplst)
t1

(1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400)

**42. With a given tuple (1,2,3,4,5,6,7,8,9,10), write a program to print the first half values in one line and the last half values in one line.
Hints: Use [n1:n2] notation to get a slice from a tuple.**

In [42]:
t1=(1,2,3,4,5,6,7,8,9,10)
print(t1[0:5])
print(t1[5:])

(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)


**43. Write a program to generate and print another tuple whose values are even numbers in the given tuple (1,2,3,4,5,6,7,8,9,10).
Hints: Use "for" to iterate the tuple. Use tuple() to generate a tuple from a list.**

In [43]:
t1=(1,2,3,4,5,6,7,8,9,10)
l1=[]
for i in t1:
    if((i%2)==0):
        l1.append(i)
t2=tuple(l1)
t2

(2, 4, 6, 8, 10)

**44. Write a program which accepts a string as input to print "Yes" if the string is "yes" or "YES" or "Yes", otherwise print "No".
Hints: Use if statement to judge condition.**

In [44]:
s1=input("Enter the input :")
if (s1.lower()=="yes"):
    print("Yes")
else:
    print("No")

Enter the input :yes
Yes


**45. Write a program which can filter even numbers in a list by using filter function. The list is: [1,2,3,4,5,6,7,8,9,10].
Hints: use filter() to filter some elements in a list. Use lambda to define anonymous functions.**

In [45]:
l1=list(filter(lambda i: i%2==0,[1,2,3,4,5,6,7,8,9,10]))
l1

[2, 4, 6, 8, 10]

**46. Write a program which can map() to make a list whose elements are square of elements in [1,2,3,4,5,6,7,8,9,10].
Hints: Use map() to generate a list. Use lambda to define anonymous functions.**

In [46]:
l1=list(map(lambda i: i**2,[1,2,3,4,5,6,7,8,9,10]))
l1

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

**47. Write a program which can map() and filter() to make a list whose elements are square of even number in [1,2,3,4,5,6,7,8,9,10].
Hints: Use map() to generate a list. Use filter() to filter elements of a list. Use lambda to define anonymous functions.**

In [47]:
l1=list(filter(lambda j: j%2==0,list(map(lambda i: i**2,[1,2,3,4,5,6,7,8,9,10]))))
l1

[4, 16, 36, 64, 100]

**48. Write a program which can filter() to make a list whose elements are even number between 1 and 20 (both included).Hints: Use filter() to filter elements of a list. Use lambda to define anonymous functions.**

In [48]:
list1=(list(filter(lambda i: i%2==0,range(1,21))))
list1

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

**49. Write a program which can map() to make a list whose elements are square of numbers between 1 and 20 (both included).
Hints: Use map() to generate a list. Use lambda to define anonymous functions.**

In [49]:
list1=(list(map(lambda i: i**2,range(1,21))))
list1

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

**50. Define a class named American which has a static method called printNationality.
Hints: Use @staticmethod decorator to define class static method.**

In [50]:
class American:
    @staticmethod
    def printNationality():
        print("My nationality is american")
American().printNationality()

My nationality is american


**51. Define a class named American and its subclass NewYorker.
Hints: Use class Subclass(ParentClass) to define a subclass.**

In [53]:
class American:
    def __init__(self):
        pass
class NewYorker(American):
    def __init__(self):
        pass

**52. Define a class named Circle which can be constructed by a radius. The Circle class has a method which can compute the area.
Hints: Use def methodName(self) to define a method.**

In [54]:
class Circle:
    def __init__(self,radius):
        self.radius=radius
    def findarea(self):
        area=3.14*(self.radius**2)
        print(area)
c1=Circle(3)
c1.findarea()

28.26


**53. Define a class named Rectangle which can be constructed by a length and width. The Rectangle class has a method which can compute the area.
Hints: Use def methodName(self) to define a method.**

In [55]:
class Rectangle:
    def __init__(self,length,width):
        self.length=length
        self.width=width
    def findarea(self):
        area=self.length*self.width
        print(area)
r1=Rectangle(3,4)
r1.findarea()

12


**54. Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have a area function which can print the area of the shape where Shape's area is 0 by default.
Hints: To override a method in super class, we can define a method with the same name in the super class.**

In [56]:
class shape:                                
    def __init__(self):
        print("this is root class")
    def area():
        print('Default area of the shapes is zero')
class square(shape):
    def __init__(self,length=0): #define default parameter. length =0, default value for area 0
        self.length=length
    def area(self):
        sqarea=self.length*self.length
        print(sqarea)
s1=square(4)
s1.area()

16


**55. Write a function to compute 5/0 and use try/except to catch the exceptions.
Hints: Use try/except to catch exceptions.**

In [57]:
def by_zero(a,b):
    try:
        c=a/b
    except:
            print("divide by zero error")
by_zero(5,0)    

divide by zero error


**56. Define a custom exception class which takes a string message as attribute.
Hints: To define a custom exception, we need to define a class inherited from Exception.**

In [58]:
class Custom(Exception):
    def __init__(self,message):
        self.message=message
raise Custom('Zerovalue')

Custom: Zerovalue

**57. Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the user name of a given email address. Both user names and company names are composed of letters only.
If the following email address is given as input to the program: Chandra@analytixlabs.com
Then, the output of the program should be: ChandraHints: Use \w to match letters. In case of input data being supplied to the question, it should be assumed to be a console input.
**

In [59]:
import re
email=input("enter the email address")
regexpat=r'([\w\.-]+)@([\w\.-]+)'
match=re.search(regexpat,email)
if not match is None:
    print (match.group(1))
else:
    print("Did not match")

enter the email addressChandra@analytixlabs.com
Chandra


**58. Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the company name of a given email address. Both user names and company names are composed of letters only.
If the following email address is given as input to the program: Chandra@analytixlabs.com
Then, the output of the program should be: analytixlabs
In case of input data being supplied to the question, it should be assumed to be a console input.Hints: Use \w to match letters**

In [60]:
import re
email=input("enter the email address")
regexpat=r'([\w\.-]+)@([\w-]+)'
match=re.search(regexpat,email)
if not match is None:
    print (match.group(2))
else:
    print("Did not match")

enter the email addressChandra@analytixlabs.com
analytixlabs


**59. Write a program which accepts a sequence of words separated by whitespace as input to print the words composed of digits only.
If the following words are given as input to the program: 2 cats and 3 dogs.
Then, the output of the program should be: ['2', '3']
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: Use re.findall() to find all substring using regex.
**

In [61]:
inpt1=input("Enter the mix of digits and strings seperated by white space :")
digits=re.findall(r'\d',inpt1)
digits

Enter the mix of digits and strings seperated by white space :2 cats and 3 dogs


['2', '3']

**60. Print a unicode string "hello world".
Hints: Use u'strings' format to define unicode string.**

In [62]:
str1=u'Hello world'
str1

'Hello world'

**61. Write a program to read an ASCII string and to convert it to a unicode string encoded by utf-8.
Hints: Use unicode() function to convert.**


In [63]:
str1=input("Enter the string : ")  ## is there any other function
#str1="104 101 108 108 111 032 119 111 114 108 100"
str2=str1.encode('utf-8') # unicode to str
str2

Enter the string : 104 101 108 108 111 032


b'104 101 108 108 111 032'

**62. Write a special comment to indicate a Python source code file is in unicode.**

In [64]:
# coding=<utf-8>

**63. Write a program to compute 1/2+2/3+3/4+...+n/n+1 with a given n input by console (n>0).
If the following n is given as input to the program: 5
Then, the output of the program should be: 3.55  In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: Use float() to convert an integer to a float**

In [65]:
n1=input("enter the value n")
n=int(n1)
tot=0
for i in range(1,n+1):
    tot=tot+(i/(i+1))
print(tot)    

enter the value n5
3.5500000000000003


**64. Write a program to compute:
f(n)=f(n-1)+100 when n>0
and f(0)=1
with a given n input by console (n>0).
If the following n is given as input to the program: 5
Then, the output of the program should be: 500
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: We can define recursive function in Python.**

In [66]:
def calfun(n): ######################## how does it come to 500???????????????/
    if (n==0):
        return 1
    else:
        return(calfun(n-1)+100)

n2=input("enter the n value :")
n=int(n2)
calfun(n)

enter the n value :5


501

**65. The Fibonacci sequence is computed based on the following formula:
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program to compute the value of f(n) with a given n input by console.
If the following n is given as input to the program: 7
Then, the output of the program should be: 13
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: We can define recursive function in Python.**

In [67]:
def fibseq(n):
    if n<=1:
        return n
    else:
        return(fibseq(n-1) + fibseq(n-2))
        
    
n1=input("Enter the n value ")
n=int(n1)
print(fibseq(n))

Enter the n value 7
13


**66. The Fibonacci sequence is computed based on the following formula:
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program using list comprehension to print the Fibonacci sequence in comma separated form with a given n input by console.
If the following n is given as input to the program: 7
Then, the output of the program should be: 0, 1, 1, 2, 3, 5, 8, 13
Hints: We can define recursive function in Python. Use list comprehension to generate a list from an existing list. Use string.join() to join a list of strings. In case of input data being supplied to the question, it should be assumed to be a console input.**

In [68]:
def fibseq(n):
    if n<=1:
        return n
    else:
        return(fibseq(n-1) + fibseq(n-2))   
n1=input("Enter the n value :")
n=int(n1)
a=[fibseq(i) for i in range(n+1)]
a

Enter the n value :7


[0, 1, 1, 2, 3, 5, 8, 13]

**67. Please write a program using generator to print the even numbers between 0 and n in comma separated form while n is input by console.
Example: If the following n is given as input to the program: 10
Then, the output of the program should be: 0,2,4,6,8,10
Hints: Use yield to produce the next value in generator. In case of input data being supplied to the question, it should be assumed to be a console input.**

In [69]:
def evengen(n):
    for i in range(0,n+1,2):
        if(i%2==0):
            yield i
            #print(i)
###########################################
n1=input("enter the upper limit")
n=int(n1)
l1=[]
##########################################
e1=evengen(n)
for i in e1:
    l1.append(i)
# myString = ", ".join(map(str, l1))
# myString
l1

enter the upper limit10


[0, 2, 4, 6, 8, 10]

**68. Please write a program using generator to print the numbers which can be divisible by 5 and 7 between 0 and n in comma separated form while n is input by console.
If the following n is given as input to the program: 100
Then, the output of the program should be: 0, 35, 70
Hints: Use yield to produce the next value in generator. In case of input data being supplied to the question, it should be assumed to be a console input.**

In [70]:
def evengen(n):
    for i in range(n+1):
        if((i%5==0) and (i%7==0)):
            yield i
            #print(i)
###########################################
n1=input("enter the upper limit: ")
n=int(n1)
l1=[]
##########################################
e1=evengen(n)
for i in e1:
    l1.append(i)
l1

enter the upper limit: 100


[0, 35, 70]

**69. Please write assert statements to verify that every number in the list [2,4,6,8] is even.
Hints: Use "assert expression" to make assertion.**

In [71]:
l1=[2,4,6,8]
for i in l1:
    assert i%2==0,"list has an odd number"

**70. Please write a program which accepts basic mathematic expression from console and print the evaluation result.
If the following string is given as input to the program: 35+3
Then, the output of the program should be: 38
Hints: Use eval() to evaluate an expression.**

In [72]:
s1=input("enter the expression")
print(eval(s1))

enter the expression35+3
38


**71. Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list.
Hints: Use if/elif to deal with conditions.**

In [73]:
def binarySearch (arr, l, r, x): 
    if r >= l: 
        mid = int(l + (r - l)/2)
        if arr[mid] == x: 
            return mid        
        elif arr[mid] > x: 
            return binarySearch(arr, l, mid-1, x)  
        else: 
            return binarySearch(arr, mid + 1, r, x)  
    else: 
        return -1   
list1=input("Enter the list of numbers :")
list1=list1.split(',')
x = [int(float(i)) for i in list1]
number= int(input("Enter the number to search : "))
result = binarySearch(x, 0, len(x)-1, number) 
if result != -1: 
    print("Element is present at index " + str(result))
else: 
    print("Element is not present in array")

Enter the list of numbers :1,2,3,4,5,6
Enter the number to search : 3
Element is present at index 2


**72. Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list.
Hints: Use if/elif to deal with conditions.**

In [74]:
###########   Same as prev qstn ######################
def binarySearch (arr, l, r, x): 
    if r >= l: 
        mid = int(l + (r - l)/2)
        if arr[mid] == x: 
            return mid        
        elif arr[mid] > x: 
            return binarySearch(arr, l, mid-1, x)  
        else: 
            return binarySearch(arr, mid + 1, r, x)  
    else: 
        return -1   
list1=input("Enter the list of numbers :")
list1=list1.split(',')
x = [int(float(i)) for i in list1]
number= int(input("Enter the number to search : "))
result = binarySearch(x, 0, len(x)-1, number) 
if result != -1: 
    print("Element is present at index " + str(result))
else: 
    print("Element is not present in array")

Enter the list of numbers :1,2,3,4,5,6
Enter the number to search : 5
Element is present at index 4


**73. Please generate a random float where the value is between 10 and 100 using Python math module.
Hints: Use random.random() to generate a random float in [0,1].**

In [75]:
import random
a=random.uniform(10,100)
a

13.23852215610912

**74. Please generate a random float where the value is between 5 and 95 using Python math module.
Hints: Use random.random() to generate a random float in [0,1].**

In [76]:
import random
a=random.uniform(5,95)
a

43.16244422418246

**75. Please write a program to output a random even number between 0 and 10 inclusive using random module and list comprehension.
Hints: Use random.choice() to a random element from a list
**

In [77]:
l1=[i for i in range(0,11) if(i%2==0)]
random.choice(l1)

4

**76. Please write a program to output a random number, which is divisible by 5 and 7, between 0 and 10 inclusive using random module and list comprehension.
Hints: Use random.choice() to a random element from a list.**

In [78]:
l1=[i for i in range(0,100) if((i%5==0) and (i%7==0))] # have modified the range, since no such an integer exist for this condition and range
random.choice(l1)

0

**77. Please write a program to generate a list with 5 random numbers between 100 and 200 inclusive.
Hints: Use random.sample() to generate a list of random values.**

In [79]:
l1=[i for i in range(100,201)]
random.sample(l1,5)

[190, 153, 166, 141, 184]

**78. Please write a program to randomly generate a list with 5 even numbers between 100 and 200 inclusive.
Hints: Use random.sample() to generate a list of random values.**

In [80]:
l1=[i for i in range(100,201) if(i%2==0)]
random.sample(l1,5)

[150, 128, 162, 144, 168]

**79. Please write a program to randomly generate a list with 5 numbers, which are divisible by 5 and 7 , between 1 and 1000 inclusive.
Hints: Use random.sample() to generate a list of random values.**

In [81]:
l1=[i for i in range(0,1000) if((i%5==0) and (i%7==0))]
random.sample(l1,5)

[665, 595, 0, 420, 770]

**80. Please write a program to randomly print a integer number between 7 and 15 inclusive.
Hints: Use random.randrange() to a random integer in a given range.**

In [82]:
random.randrange(7,16)

10

**81. Please write a program to compress and decompress the string "hello world!hello world!hello world!hello world!".
Hints: Use zlib.compress() and zlib.decompress() to compress and decompress a string.**

In [83]:
import zlib
data="hello world!hello world!hello world!hello world!"
binary=data.encode('ascii')
comp_data=zlib.compress(binary)
print(comp_data)
s2=zlib.decompress(comp_data)
print(s2.decode())

b'x\x9c\xcbH\xcd\xc9\xc9W(\xcf/\xcaIQ\xcc \x82\r\x00\xbd[\x11\xf5'
hello world!hello world!hello world!hello world!


**82. Please write a program to print the running time of execution of "1+1" for 100 times.
Hints: Use timeit() function to measure the running time.**

In [84]:
import timeit
def add2():
    a=1+1
sec1=timeit.timeit(stmt=add2,number=100)
sec1

8.782999998402374e-06

**83. Please write a program to shuffle and print the list [3,6,7,8].
Hints: Use shuffle() function to shuffle a list.**

In [85]:
import random
l1=[3,6,7,8]
random.shuffle(l1)
l1

[6, 3, 8, 7]

**84. Please write a program to shuffle and print the list [3,6,7,8].
Hints: Use shuffle() function to shuffle a list.**

In [86]:
#repeat of qstn number 83
import random
l1=[3,6,7,8]
random.shuffle(l1)
l1

[3, 6, 7, 8]

**85. Please write a program to generate all sentences where subject is in ["I", "You"] and verb is in ["Play", "Love"] and the object is in ["Hockey","Football"].
Hints: Use list[index] notation to get a element from a list.**

In [87]:
sub=["I","You"]
verb=["Play","Love"]
obj=["Hockey","Football"]
for i in sub:
    for j in verb:
        for k in obj:
            print((i +" "+ j+" " + k))       

I Play Hockey
I Play Football
I Love Hockey
I Love Football
You Play Hockey
You Play Football
You Love Hockey
You Love Football


**86. Please write a program to print the list after removing delete even numbers in [5,6,77,45,22,12,24].
Hints: Use list comprehension to delete a bunch of element from a list.**

In [88]:
ls1=[5,6,77,45,22,12,24]
ls2=[i for i in ls1 if(i%2!=0)]
ls2

[5, 77, 45]

**87. By using list comprehension, please write a program to print the list after removing delete numbers which are divisible by 5 and 7 in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list.**

In [89]:
ls1=[12,24,35,70,88,120,155]
ls2=[i for i in ls1 if((i%5!=0) and (i%7!=0))]
ls2

[12, 24, 88]

**88. By using list comprehension, please write a program to print the list after removing the 0th, 2nd, 4th,6th numbers in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple.**

In [90]:
l1=[12,24,35,70,88,120,155]
l4=[0,2,4,6]
l2=list(enumerate(l1))
l3=[x[1] for x in l2 if (x[0] not in l4)]
l3

[24, 70, 120]

**89. By using list comprehension, please write a program generate a 3*5*8 3D array whose each element is 0.
Hints: Use list comprehension to make an array.**

In [91]:
arr = [[[0 for k in range(8)] for j in range(5)] for i in range(3)]
arr

[[[0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0]]]

**90. By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple.**

In [92]:
l1=[12,24,35,70,88,120,155]
l4=[0,4,5]
l2=list(enumerate(l1))
l3=[x[1] for x in l2 if (x[0] not in l4)]
l3

[24, 35, 70, 155]

**91. By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155].
Hints: Use list's remove method to delete a value.**

In [93]:
l1=[12,24,35,24,88,120,155] #### Remove deletes only the first encounter####
l1.remove(24)
l1

[12, 35, 24, 88, 120, 155]

**92. With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists.
Hints: Use set() and "&=" to do set intersection operation.**

In [94]:
l1=[1,3,6,78,35,55]
l2=[12,24,35,24,88,120,155]
s1=set(l1)
s2=set(l2)
s1&=s2
s1

{35}

**93. With a given list [12, 24, 35, 24, 88, 120, 155, 88, 120, 155], write a program to print this list after removing all duplicate values with original order reserved.
Hints: Use set() to store a number of values without duplicate.**

In [95]:
lst1=[12, 24, 35, 24, 88, 120, 155, 88, 120, 155]
lst2=list(set(lst1))
lst2

[35, 12, 155, 24, 88, 120]

**94. Define a class Person and its two child classes: Male and Female. All classes have a method "getGender" which can print "Male" for Male class and "Female" for Female class.
Hints: Use Subclass(Parentclass) to define a child class.**

In [96]:
class Person:
    def __init__(self,gender):
        self.gender=gender

class Male(Person):
    def __init__(self):
        super.__inti__(Person.gender)
        
    def getGender(self):
        if self.gender=='M':
            print("Male")

class Female(Person):
    def getGender(self):
        if self.gender=='F':
            print("Female")

**95. Please write a program which count and print the numbers of each character in a string input by console.
If the following string is given as input to the program: abcdefgabc
Then, the output of the program should be:
a,2
c,2
b,2
e,1
d,1
g,1
f,1
Hints: Use dict to store key/value pairs. Use dict.get() method to lookup a key with default value.**

In [97]:
str1=input("Enter the string to be conuted")
dict1=dict()
for i in str1:
    cnt=str1.count(i)
    dict1.update({i:cnt})
for i in dict1.keys():
    print(i,dict1.get(i))

Enter the string to be conutedabcdefgabc
a 2
b 2
c 2
d 1
e 1
f 1
g 1


**96 Please write a program which accepts a string from console and print it in reverse order.
If the following string is given as input to the program: rise to vote sir
Then, the output of the program should be: ris etov ot esir
Hints: Use list[::-1] to iterate a list in a reverse order.**

In [98]:
strip=input("Enter the sentence to reverse")
strrs=strip[::-1]
strrs

Enter the sentence to reverserise to vote sir


'ris etov ot esir'

**97. Please write a program which accepts a string from console and print the characters that have even indexes.
If the following string is given as input to the program: H1e2l3l4o5w6o7r8l9d
Then, the output of the program should be: Helloworld
Hints: Use list[::2] to iterate a list by step 2.**

In [99]:
str1=input("enter the string")
str2=str1[::2]
str2

enter the stringH1e2l3l4o5w6o7r8l9d


'Helloworld'

**98. Please write a program which prints all permutations of [1, 2, 3]
Hints: Use itertools.permutations() to get permutations of list.**

In [100]:
#from more_itertools import circular_shifts
import itertools
lst=[1,2,3]
print(list(itertools.permutations(lst)))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


**99. Write a program to solve a classic ancient Chinese puzzle:
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?  Hint: Use for loop to iterate all possible solutions**

In [101]:
for i in range(1,36):
    for j in range(36-i):
        if((2*i)+(4*j)==94):
            print(i,j)

1 23
3 22
5 21
7 20
9 19
11 18
13 17
15 16
17 15
19 14
21 13
23 12


**100. Create a dictionary with phone numbers (phonebook = {“John”: 938477566, "Jack”: 938377264, "Jill”: 947662781}). Add "Jake" to the phonebook with the phone number 938273443, and remove Jill from the phonebook**

In [102]:
phnbk={"John": 938477566,"Jack": 938377264,"Jill": 947662781}
print(phnbk)
phnbk.update({"jake":938273443})
print(phnbk)
del phnbk["Jill"]
print(phnbk)

{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781}
{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781, 'jake': 938273443}
{'John': 938477566, 'Jack': 938377264, 'jake': 938273443}
